language: objective-c
install: ''
osx_image: xcode7.2

env:
  global:
    # Offset build number to prevent duplicate version errors from iTunes
    - TRAVIS_BUILD_NUMBER_OFFSET=150
		 # FASTLANE_PASSWORD
    - secure:   "WFSJwZsCj4QQ3Hrxz1igDgHwRTnskhCI3mhJbgO/VaW9a9VhhtfUpvrbbpFrwJmPQPH9bepGulEab770ndyJ8F4AsB6UJqrKZjmMPw3dyAo8gd0NHvwCxu9z3hXBuUno2r/Fbc3mFs+ACiR+JghOUt/zsJ1Q+FhKy1Pd8G2XRpfDB3tujKuVOI0xDg91CVVk9GayHO/Uoz5EHlWUG+IlZ2pSJdfn16wACUBhhr3xowizSxed6KtaSNX1Yc5RyQ+WV0NQGE6mjFO6zpo90s7DRxpIruoIdmHNP+I4SQDYzgI/WCOJkf+ewgtr/mVEEaWeFDM40VUJcYGg6SzVVFcbO5+BjXhONK23XepWpuey61m5rMSSmR62hGbs7pNxqKC3aCU5xSBsA16QICaNql0xu/gxxODfytzkB2fB2xHd/A2TKTHJ/766BJcJJNxRrio1y2D6HpYliSLqFUFPDfmlTASNBHQhbe9Pl68k5meTPmLRGW/nkpIzjAGI3Ux2LWG5q7Hdcu6OSDlmCvV/G41uCAlcX5ZPUGwetZrkh2PGfsHO+n1fGXlbjUKLgFTTbAh7F7Yv1pLreep9bf8t0/Fe543h1R1GjjHVOf6Ic+kk/Ys3w3RBEJNWikajoUiUa6ob81asa8H+IfD4Edx1wK9fMPkIZ8Zrd9uyvThIef+rlA0="

before_install:
  # Reinstall Ruby to avoid SSL errors when publishing to iTunes
  - rvm reinstall 2.0.0-p643 --disable-binary
  - bundle install
  - ./ci/start_simulator.sh

before_script:
  - ./ci/tag_build.sh

script:
  - ./ci/test_and_publish.sh

after_success:
  - ./ci/push_tag.sh
  - ./ci/send_release_email.rb
  - ./ci/generate_screenshots.sh

# Don't build tags generated by CI, which are numeric
branches:
  except:
    - /^[0-9]*$/
