platform :ios, '8.0'

link_with 'MyReddit', 'MyRedditTests', 'MyRedditUITests'

pod 'Localytics-AMP', '~> 2.0'
pod 'RedditKit'
pod 'SDWebImage'
pod 'XNGMarkdownParser'
pod 'BDGInAppPurchase'
pod 'MBProgressHUD'
pod 'JZSwipeCell', '~> 1.1'
pod 'ImgurAnonymousAPIClient'
pod 'NSDate+Calendar'
pod 'ImgurSession'
pod 'Appirater'
pod 'DateTools'
pod 'RATreeView'
pod 'Google-Mobile-Ads-SDK'
pod 'TTTAttributedLabel'
pod 'AMScrollingNavbar', '~> 2.0.1'
pod 'KeychainAccess'
pod 'MNGAds', '~> 2.0'
pod 'GoogleConversionTracking'
pod 'AdMobMediationAdapterFB'
pod 'Fabric'
pod 'Crashlytics'

use_frameworks!
